package config

import (
	"embed"
	"encoding/json"
	"fmt"
	"path/filepath"

	libconfig "github.com/Diaphteiros/kw/pluginlib/pkg/config"
	libutils "github.com/Diaphteiros/kw/pluginlib/pkg/utils"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/apimachinery/pkg/util/validation/field"
	"sigs.k8s.io/yaml"
)

var (
	BuiltinSubcommands sets.Set[string]  // set of built-in subcommand names
	BuiltinAliases     map[string]string // map of built-in subcommand aliases as keys, mapped to the subcommands they belong to
)

const ConfigFileName = "config.yaml"

//go:embed default
var defaultConfigDir embed.FS

type Config struct {
	Kubeswitcher *KubeswitcherConfig `json:"kubeswitcher"`
	Builtin      *BuiltinConfig      `json:"builtin,omitempty"`
	Plugins      PluginConfigList    `json:"plugins,omitempty"`
}

type KubeswitcherConfig struct {
	// KubectlBinary is the path to the kubectl binary to use.
	// If not set, "kubectl" is used and is expected to be resolvable via $PATH.
	KubectlBinary string `json:"kubectlBinary,omitempty"`
	// PrintInfoOnKubeconfigChange controls whether a message is printed if the kubeconfig changed.
	PrintInfoOnKubeconfigChange bool `json:"printInfoOnKubeconfigChange"`
	// PrintChangeInfoToStderr controls whether the info message is printed to stderr or stdout.
	PrintChangeInfoToStderr bool `json:"printChangeInfoToStderr"`
	// HistoryDepth controls how many entries are stored in the history.
	// If set to 0, the history is disabled.
	HistoryDepth int `json:"historyDepth"`
}

type BuiltinConfig struct {
	Custom *BuiltinCustomConfig `json:"custom,omitempty"`
}

type BuiltinCustomConfig struct {
	// MaxIdLength is the maximum length of the id that is generated by the 'custom' subcommand.
	// Usually, the id is 'custom:' followed by the path to the kubeconfig.
	// Since this can get somewhat long and the id is meant to be displayed in the shell prompt, it can be shortened.
	// This value affects only the path part of the id, not the prefix, and it cuts off the beginning of the path.
	// Example: The path '/foo/bar/baz' could lead to the id 'custom:…ar/baz' if the max length is set to 6.
	// The total length of the id will be maxIdLength + 8.
	// If set to 0 or a negative value, the id will not be shortened.
	MaxIdLength int `json:"maxIdLength,omitempty"`
}

type PluginConfigList []*PluginConfig

type PluginConfig struct {
	// Name of the plugin and also the subcommand.
	Name string `json:"name"`
	// Aliases for the subcommand.
	// Optional.
	Aliases []string `json:"aliases,omitempty"`
	// Binary is the path to the binary for the plugin.
	// Must be either an absolute path or resolvable via $PATH.
	Binary string `json:"binary"`
	// Short description of the plugin to display on 'kw --help'.
	Short string `json:"short"`
	// Config contains plugin-specific configuration.
	// Optional.
	Config json.RawMessage `json:"config,omitempty"`
	// Env contains environment variables to set before running the plugin.
	// Optional.
	Env map[string]string `json:"env,omitempty"`
}

func LoadConfig() (*Config, error) {
	defaultCfg, err := defaultConfigDir.ReadFile(filepath.Join("default", ConfigFileName))
	if err != nil {
		return nil, fmt.Errorf("unable to read default config: %w", err)
	}
	cfg := &Config{}
	if err := libconfig.LoadConfig(cfg, Runtime.ConfigDirectory(), ConfigFileName, defaultCfg); err != nil {
		return nil, fmt.Errorf("unable to load config: %w", err)
	}
	return cfg, nil
}

func (c *Config) String() string {
	data, err := yaml.Marshal(c)
	if err != nil {
		libutils.Fatal(1, "unable to marshal config: %w\n", err)
	}
	return string(data)
}

func (c *Config) Default() error {
	if c.Kubeswitcher == nil {
		c.Kubeswitcher = &KubeswitcherConfig{
			HistoryDepth: 5,
		}
	}
	if c.Kubeswitcher.KubectlBinary == "" {
		c.Kubeswitcher.KubectlBinary = "kubectl"
	}
	return nil
}

func (c *Config) Validate() error {
	errs := field.ErrorList{}
	fldPath := field.NewPath("kubeswitcher")
	if c.Kubeswitcher == nil {
		errs = append(errs, field.Required(fldPath, "kubeswitcher config must not be nil"))
	} else {
		if c.Kubeswitcher.HistoryDepth < 0 {
			errs = append(errs, field.Invalid(fldPath.Child("historyDepth"), c.Kubeswitcher.HistoryDepth, "history depth must not be negative"))
		} else if c.Kubeswitcher.HistoryDepth > 50 {
			errs = append(errs, field.Invalid(fldPath.Child("historyDepth"), c.Kubeswitcher.HistoryDepth, "history depth must not be greater than 50"))
		}
	}

	fldPath = field.NewPath("plugins")
	errs = append(errs, c.Plugins.validate(fldPath)...)

	return errs.ToAggregate()
}

func (pcl PluginConfigList) validate(fldPath *field.Path) field.ErrorList {
	if len(pcl) == 0 {
		return nil
	}
	errs := field.ErrorList{}
	pluginNames := sets.New[string]()
	pluginAliases := sets.New[string]()

	for i, pc := range pcl {
		curPath := fldPath.Index(i)

		// name
		if pc.Name == "" {
			errs = append(errs, field.Required(curPath.Child("name"), "plugin name must not be empty"))
		}
		if pluginNames.Has(pc.Name) {
			errs = append(errs, field.Duplicate(curPath.Child("name"), pc.Name))
		}
		if BuiltinSubcommands.Has(pc.Name) {
			errs = append(errs, field.Invalid(curPath.Child("name"), pc.Name, "plugin name must not be a built-in subcommand"))
		}
		pluginNames.Insert(pc.Name)

		// aliases
		if len(pc.Aliases) > 0 {
			for j, alias := range pc.Aliases {
				aliasPath := curPath.Child("aliases").Index(j)
				if alias == "" {
					errs = append(errs, field.Required(aliasPath, "plugin alias must not be empty"))
				}
				if pluginAliases.Has(alias) {
					errs = append(errs, field.Duplicate(aliasPath, alias))
				}
				if conflict, ok := BuiltinAliases[alias]; ok {
					errs = append(errs, field.Invalid(aliasPath, alias, fmt.Sprintf("plugin alias conflicts with an alias for the built-in subcommand '%s'", conflict)))
				}
				pluginAliases.Insert(alias)
			}
		}

		// binary
		if pc.Binary == "" {
			errs = append(errs, field.Required(curPath.Child("binary"), "plugin binary must not be empty"))
		}

		// short
		if pc.Short == "" {
			errs = append(errs, field.Required(curPath.Child("short"), "plugin short description must not be empty"))
		}
	}

	return errs
}

// GetBuiltinCustomConfig is a getter method that will not panic on a nil receiver.
func (c *BuiltinConfig) GetBuiltinCustomConfig() *BuiltinCustomConfig {
	if c == nil {
		return nil
	}
	return c.Custom
}
